services:
  mysql:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      VITE_API_BASE_URL: /api
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/myapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password123
    volumes:
      - npm_cache:/root/.npm

volumes:
  db_data:
  npm_cache: